openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0

paths:
  /example:
    post:
      description: Get example by id
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: object
            required:
              - login
              - password
              - uuuid_session
            properties:
              login:
                type: string
              password:
                type: string
              uuid_session:
                type: string
      responses:
        "200":
          description: Example retrieved
          content:
            application/json:
              schema:
                type: object
                required:
                  - login
                  - password
                  - uuuid_session
                properties:
                  login:
                    type: string
                  password:
                    type: string
                  uuid_session:
                    type: string
    

  /test:
    post:
      description: Get example by id
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: object
            required:
              - login
              - password
              - uuuid_session
            properties:
              login:
                type: string
              password:
                type: string
              uuid_session:
                type: string
      responses:
        "200":
          description: Example retrieved
          content:
            application/json:
              schema:
                type: object
                required:
                  - login
                  - password
                  - uuuid_session
                properties:
                  login:
                    type: string
                  password:
                    type: string
                  uuid_session:
                    type: string
    

